menu:
    home: /
    blog: /archives/
    rss: /atom.xml
    github: https://github.com/pyweek/pyweek.github.io
    news: /news/
    bang: /bang/
    challenges: /challenges/
    help: /help/

favicon: /favicon.png

google_analytics:
baidu_analytics:

selfIntro:
    title: 每周实战一题，每周前进一步
    content: 贵以恒,何必三更眠五更起；最无益,只怕一日曝十日寒。
    social:
        github: https://github.com/pyweek/pyweek.github.io

